-- 作業2

-- 1
SELECT ENAME,SAL from emp where SAL>2850;

-- 2
SELECT ENAME,DEPTNO FROM emp where EMPNO=7566;

-- 3
SELECT ENAME,SAL FROM emp where SAL NOT BETWEEN 1500 AND 2850;

-- 4
SELECT ENAME,JOB,HIREDATE 
FROM emp 
WHERE HIREDATE BETWEEN 20110220 AND 20110501 
ORDER BY HIREDATE ASC;

-- 5
SELECT ENAME,DEPTNO 
FROM emp
WHERE DEPTNO IN (10,30)
ORDER BY ENAME;

-- 6
SELECT ENAME as Employee,SAL as 'Monthly Salary'
FROM emp
WHERE SAL>1500 and DEPTNO IN (10,30);

-- 7
SELECT ENAME,JOB,HIREDATE
FROM emp
WHERE HIREDATE LIKE '2012-%';

-- 8
SELECT ENAME,JOB
FROM emp
WHERE MGR IS NULL;

-- 9
SELECT ENAME,SAL,COMM
FROM emp
WHERE COMM >'0'
ORDER BY SAL DESC,COMM DESC;

-- 10
SELECT ENAME,JOB
FROM emp
WHERE ENAME LIKE'__A%';

-- 11
SELECT ENAME,MGR,DEPTNO
FROM emp
WHERE ENAME LIKE'%L%L%' AND DEPTNO=30 OR MGR='7782';

-- 12
SELECT ENAME,JOB,SAL 
FROM emp
WHERE (JOB='Clerk'or JOB='Analyst') and SAL not in(1000,3000,5000);

-- 13
SELECT ENAME,SAL,COMM
FROM emp
WHERE COMM > (SAL*1.1);



 

 

