-- 作業八

-- 1
CREATE TABLE DEPARTMENT
(id	int		NOT NULL, 
 name	varchar(24)	NOT NULL);
desc department;
 
 -- 2
INSERT INTO DEPARTMENT(id,name)
	SELECT DEPTNO,DNAME
	FROM demo.dept;
    
-- 3
CREATE TABLE EMPLOYEE
(id		INT		NOT NULL,
 last_name	varchar(24)	NOT NULL,
 first_name	varchar(24),
 dept_id	INT);
DESC EMPLOYEE;
 
-- 4
ALTER TABLE EMPLOYEE
MODIFY last_name varchar(40);
DESC EMPLOYEE;
 
-- 5
CREATE TABLE EMPLOYEE2
 AS
 SELECT EMPNO AS ID,ENAME AS LAST_NAME,DEPTNO AS DEPT_ID
 FROM emp;
DESC EMPLOYEE2;
 
-- 6
DROP TABLE EMPLOYEE;

-- 7
ALTER TABLE EMPLOYEE2
RENAME TO EMPLOYEE;
DESC EMPLOYEE;

-- 8
ALTER TABLE EMPLOYEE
DROP LAST_NAME;
DESC EMPLOYEE;

-- 9
ALTER TABLE EMPLOYEE
ADD SALARY INT;
desc EMPLOYEE;

-- 10
ALTER TABLE EMPLOYEE
ADD CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY(ID); 
SHOW INDEXES FROM employee;
 
-- 11
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_DEPT_ID FOREIGN KEY(DEPT_ID)		
                                   REFERENCES DEPT(DEPTNO) ON UPDATE RESTRICT;
SHOW INDEXES FROM employee;