
-- 1
CREATE VIEW EMP_VU
AS
 SELECT empno,ename as EMPLOYEE,deptno
 FROM emp;
    
-- 2
SELECT *
FROM EMP_VU;

-- 3
SELECT EMPLOYEE,deptno
FROM EMP_VU;

-- 4
CREATE VIEW  DEPT20
AS 
 SELECT EMPNO AS EMPLOYEE_ID,ENAME AS EMPLOYEE,DEPTNO AS DEPARTMENT_ID
 FROM emp
 WHERE DEPTNO=20
WITH CHECK OPTION;

-- 5
DESC DEPT20;
SELECT *
FROM DEPT20;

-- 6
UPDATE DEPT20
SET DEPARTMENT_ID=30
WHERE EMPLOYEE='Smith';

-- 7
CREATE VIEW SALARY_VU
AS
SELECT e.ENAME AS Employee,d.DNAME AS Department,e.SAL as Salary,s.Grade 
FROM emp e join salgrade s on e.SAL BETWEEN s.LOSAL AND s.HISAL
           join dept d on e.DEPTNO= d. DEPTNO;

SELECT*
FROM SALARY_VU;

    